import kotlin.String

/**
 * Generated by https://github.com/jmfayard/buildSrcVersions
 *
 * Update this file with
 *   `$ ./gradlew buildSrcVersions`
 */
object Libs {
    const val org_danilopianini_git_sensitive_semantic_versioning_gradle_plugin: String =
            "org.danilopianini.git-sensitive-semantic-versioning:org.danilopianini.git-sensitive-semantic-versioning.gradle.plugin:" +
            Versions.org_danilopianini_git_sensitive_semantic_versioning_gradle_plugin

    const val org_danilopianini_publish_on_central_gradle_plugin: String =
            "org.danilopianini.publish-on-central:org.danilopianini.publish-on-central.gradle.plugin:" +
            Versions.org_danilopianini_publish_on_central_gradle_plugin

    const val org_jlleitschuh_gradle_ktlint_gradle_plugin: String =
            "org.jlleitschuh.gradle.ktlint:org.jlleitschuh.gradle.ktlint.gradle.plugin:" +
            Versions.org_jlleitschuh_gradle_ktlint_gradle_plugin

    const val de_fayard_buildsrcversions_gradle_plugin: String =
            "de.fayard.buildSrcVersions:de.fayard.buildSrcVersions.gradle.plugin:" +
            Versions.de_fayard_buildsrcversions_gradle_plugin

    const val org_jetbrains_kotlin_jvm_gradle_plugin: String =
            "org.jetbrains.kotlin.jvm:org.jetbrains.kotlin.jvm.gradle.plugin:" +
            Versions.org_jetbrains_kotlin_jvm_gradle_plugin

    const val org_protelis_protelisdoc_gradle_plugin: String =
            "org.protelis.protelisdoc:org.protelis.protelisdoc.gradle.plugin:" +
            Versions.org_protelis_protelisdoc_gradle_plugin

    const val com_eden_orchidplugin_gradle_plugin: String =
            "com.eden.orchidPlugin:com.eden.orchidPlugin.gradle.plugin:" +
            Versions.com_eden_orchidplugin_gradle_plugin

    const val com_gradle_build_scan_gradle_plugin: String =
            "com.gradle.build-scan:com.gradle.build-scan.gradle.plugin:" +
            Versions.com_gradle_build_scan_gradle_plugin

    const val com_github_spotbugs_gradle_plugin: String =
            "com.github.spotbugs:com.github.spotbugs.gradle.plugin:" +
            Versions.com_github_spotbugs_gradle_plugin

    const val com_jfrog_bintray_gradle_plugin: String =
            "com.jfrog.bintray:com.jfrog.bintray.gradle.plugin:" +
            Versions.com_jfrog_bintray_gradle_plugin

    /**
     * https://javaeden.github.io/Orchid/latest/core/
     */
    const val orchidsyntaxhighlighter: String =
            "io.github.javaeden.orchid:OrchidSyntaxHighlighter:" + Versions.orchidsyntaxhighlighter

    /**
     * https://kotlinlang.org/
     */
    const val kotlin_scripting_compiler_embeddable: String =
            "org.jetbrains.kotlin:kotlin-scripting-compiler-embeddable:" +
            Versions.org_jetbrains_kotlin

    /**
     * https://kotlinlang.org/
     */
    const val kotlin_stdlib: String = "org.jetbrains.kotlin:kotlin-stdlib:" +
            Versions.org_jetbrains_kotlin

    /**
     * http://www.protelis.org
     */
    const val protelis_interpreter: String = "org.protelis:protelis-interpreter:" +
            Versions.protelis_interpreter

    /**
     * https://spotbugs.github.io/
     */
    const val spotbugs_annotations: String = "com.github.spotbugs:spotbugs-annotations:" +
            Versions.spotbugs_annotations

    /**
     * https://github.com/DanySK/alchemist-interfaces
     */
    const val alchemist_interfaces: String = "it.unibo.alchemist:alchemist-interfaces:" +
            Versions.it_unibo_alchemist

    /**
     * https://github.com/DanySK/alchemist-loading
     */
    const val alchemist_loading: String = "it.unibo.alchemist:alchemist-loading:" +
            Versions.it_unibo_alchemist

    /**
     * https://javaeden.github.io/Orchid/latest/core/
     */
    const val orchidplugindocs: String = "io.github.javaeden.orchid:OrchidPluginDocs:" +
            Versions.orchidplugindocs

    /**
     * http://logback.qos.ch
     */
    const val logback_classic: String = "ch.qos.logback:logback-classic:" + Versions.logback_classic

    /**
     * https://javaeden.github.io/Orchid/latest/core/
     */
    const val orchidkotlindoc: String = "io.github.javaeden.orchid:OrchidKotlindoc:" +
            Versions.orchidkotlindoc

    /**
     * http://protelis.org
     */
    const val protelis_parser: String = "org.protelis:protelis.parser:" + Versions.protelis_parser

    /**
     * https://commons.apache.org/proper/commons-codec/
     */
    const val commons_codec: String = "commons-codec:commons-codec:" + Versions.commons_codec

    /**
     * http://commons.apache.org/proper/commons-lang/
     */
    const val commons_lang3: String = "org.apache.commons:commons-lang3:" + Versions.commons_lang3

    /**
     * http://commons.apache.org/proper/commons-math/
     */
    const val commons_math3: String = "org.apache.commons:commons-math3:" + Versions.commons_math3

    /**
     * https://javaeden.github.io/Orchid/latest/core/
     */
    const val orchidgithub: String = "io.github.javaeden.orchid:OrchidGithub:" +
            Versions.orchidgithub

    /**
     * https://javaeden.github.io/Orchid/latest/core/
     */
    const val orchidsearch: String = "io.github.javaeden.orchid:OrchidSearch:" +
            Versions.orchidsearch

    /**
     * https://javaeden.github.io/Orchid/latest/core/
     */
    const val orchidbsdoc: String = "io.github.javaeden.orchid:OrchidBsDoc:" + Versions.orchidbsdoc

    /**
     * https://github.com/classgraph/classgraph
     */
    const val classgraph: String = "io.github.classgraph:classgraph:" + Versions.classgraph

    /**
     * http://commons.apache.org/proper/commons-io/
     */
    const val commons_io: String = "commons-io:commons-io:" + Versions.commons_io

    /**
     * https://javaeden.github.io/Orchid/latest/core/
     */
    const val orchidwiki: String = "io.github.javaeden.orchid:OrchidWiki:" + Versions.orchidwiki

    /**
     * http://www.slf4j.org
     */
    const val slf4j_api: String = "org.slf4j:slf4j-api:" + Versions.slf4j_api

    /**
     * http://trove4j.sf.net
     */
    const val trove4j: String = "net.sf.trove4j:trove4j:" + Versions.trove4j

    /**
     * http://www.jboss.org/apiviz/
     */
    const val apiviz: String = "org.jboss.apiviz:apiviz:" + Versions.apiviz

    /**
     * https://github.com/pinterest/ktlint
     */
    const val ktlint: String = "com.pinterest:ktlint:" + Versions.ktlint

    /**
     * https://github.com/google/guava
     */
    const val guava: String = "com.google.guava:guava:" + Versions.guava

    /**
     * http://junit.org
     */
    const val junit: String = "junit:junit:" + Versions.junit

    /**
     * http://ruedigermoeller.github.io/fast-serialization/
     */
    const val fst: String = "de.ruedigermoeller:fst:" + Versions.fst
}
